from selenium.webdriver.common.by import By

link = "http://selenium1py.pythonanywhere.com/"

def test_guest_should_see_login_link_pass(browser):
    browser.get(link)
    browser.find_element(By.CSS_SELECTOR, "#login_link")

def test_guest_should_see_login_link_fail(browser):
    browser.get(link)
    browser.find_element(By.CSS_SELECTOR, "#magic_link")

# Мы будем перезапускать упавший тест, чтобы еще раз убедиться, что он действительно нашел баг, а не упал случайно.
#
# Это сделать очень просто. Для этого мы будем использовать плагин pytest-rerunfailures.
# pip install pytest-rerunfailures,
#
# Чтобы указать количество перезапусков для каждого из упавших тестов, нужно добавить в командную строку параметр:
#
# "--reruns n", где n — это количество перезапусков. Если при повторных запусках тесты пройдут успешно,
# то и прогон тестов будет считаться успешным. Количество перезапусков отображается в отчёте, благодаря чему можно
# позже анализировать проблемные тесты.
# Дополнительно мы указали параметр "--tb=line", чтобы сократить лог с результатами теста.
#
# Давайте напишем два теста: один из них будет проходить, а другой — нет. Посмотрим, как выглядит перезапуск
# pytest -v --tb=line --reruns 1 --browser_name=chrome test_rerun.py
#
# Мы увидим сообщение: "1 failed, 1 passed, 1 rerun in 9.20s", то есть упавший тест был перезапущен,
# но при втором запуске тоже упал. Если бы во второй раз мигающий тест все-таки прошёл успешно,
# то мы бы увидели сообщение: "2 passed, 1 rerun in 9.20s", и итоговый результат запуска всех
# тестов считался бы успешным.